// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "belajar-crud-mvc/models"

	mock "github.com/stretchr/testify/mock"
)

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: input
func (_m *ProductService) CreateProduct(input models.CreateProductInput) (*models.Product, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(models.CreateProductInput) (*models.Product, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(models.CreateProductInput) *models.Product); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(models.CreateProductInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduct provides a mock function with given fields: id
func (_m *ProductService) DeleteProduct(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllProducts provides a mock function with given fields: page, limit, search, category
func (_m *ProductService) GetAllProducts(page int, limit int, search string, category string) ([]models.Product, int64, int, error) {
	ret := _m.Called(page, limit, search, category)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []models.Product
	var r1 int64
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(int, int, string, string) ([]models.Product, int64, int, error)); ok {
		return rf(page, limit, search, category)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, string) []models.Product); ok {
		r0 = rf(page, limit, search, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, string) int64); ok {
		r1 = rf(page, limit, search, category)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string, string) int); ok {
		r2 = rf(page, limit, search, category)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(int, int, string, string) error); ok {
		r3 = rf(page, limit, search, category)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetProductByID provides a mock function with given fields: id
func (_m *ProductService) GetProductByID(id uint) (*models.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: id, input
func (_m *ProductService) UpdateProduct(id uint, input models.UpdateProductInput) (*models.Product, error) {
	ret := _m.Called(id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, models.UpdateProductInput) (*models.Product, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(uint, models.UpdateProductInput) *models.Product); ok {
		r0 = rf(id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, models.UpdateProductInput) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
