// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "belajar-crud-mvc/models"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: transaction
func (_m *TransactionRepository) Create(transaction *models.Transaction) error {
	ret := _m.Called(transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction) error); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: transaction
func (_m *TransactionRepository) Delete(transaction *models.Transaction) error {
	ret := _m.Called(transaction)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction) error); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: page, limit, userID
func (_m *TransactionRepository) FindAll(page int, limit int, userID uint) ([]models.Transaction, int64, error) {
	ret := _m.Called(page, limit, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Transaction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, uint) ([]models.Transaction, int64, error)); ok {
		return rf(page, limit, userID)
	}
	if rf, ok := ret.Get(0).(func(int, int, uint) []models.Transaction); ok {
		r0 = rf(page, limit, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, uint) int64); ok {
		r1 = rf(page, limit, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, uint) error); ok {
		r2 = rf(page, limit, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *TransactionRepository) FindByID(id uint) (*models.Transaction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Transaction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Transaction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: transaction, status
func (_m *TransactionRepository) UpdateStatus(transaction *models.Transaction, status models.TransactionStatus) error {
	ret := _m.Called(transaction, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction, models.TransactionStatus) error); ok {
		r0 = rf(transaction, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
