// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "belajar-crud-mvc/models"

	mock "github.com/stretchr/testify/mock"
)

// TransactionService is an autogenerated mock type for the TransactionService type
type TransactionService struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: input
func (_m *TransactionService) CreateTransaction(input models.CreateTransactionInput) (*models.Transaction, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(models.CreateTransactionInput) (*models.Transaction, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(models.CreateTransactionInput) *models.Transaction); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(models.CreateTransactionInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTransaction provides a mock function with given fields: id
func (_m *TransactionService) DeleteTransaction(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllTransactions provides a mock function with given fields: page, limit, userID
func (_m *TransactionService) GetAllTransactions(page int, limit int, userID uint) ([]models.Transaction, int64, int, error) {
	ret := _m.Called(page, limit, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTransactions")
	}

	var r0 []models.Transaction
	var r1 int64
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(int, int, uint) ([]models.Transaction, int64, int, error)); ok {
		return rf(page, limit, userID)
	}
	if rf, ok := ret.Get(0).(func(int, int, uint) []models.Transaction); ok {
		r0 = rf(page, limit, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, uint) int64); ok {
		r1 = rf(page, limit, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, uint) int); ok {
		r2 = rf(page, limit, userID)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(int, int, uint) error); ok {
		r3 = rf(page, limit, userID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetTransactionByID provides a mock function with given fields: id
func (_m *TransactionService) GetTransactionByID(id uint) (*models.Transaction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByID")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Transaction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Transaction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTransactionStatus provides a mock function with given fields: id, input
func (_m *TransactionService) UpdateTransactionStatus(id uint, input models.UpdateTransactionStatusInput) (*models.Transaction, error) {
	ret := _m.Called(id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionStatus")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, models.UpdateTransactionStatusInput) (*models.Transaction, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(uint, models.UpdateTransactionStatusInput) *models.Transaction); ok {
		r0 = rf(id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, models.UpdateTransactionStatusInput) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionService creates a new instance of TransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionService {
	mock := &TransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
